# Generated by Django 3.2.20 on 2023-08-04 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('personal_recipe_photo', models.URLField()),
                ('type', models.IntegerField(choices=[('starter', 'STARTER'), ('main', 'MAIN'), ('dessert', 'DESSERT')])),
                ('ingredients', models.CharField(max_length=300)),
                ('cook_time', models.PositiveIntegerField()),
                ('method', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
