# Generated by Django 3.2.20 on 2023-08-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipemodel_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='type',
            field=models.IntegerField(choices=[(1, 'STARTER'), (2, 'MAIN'), (3, 'DESSERT')]),
        ),
    ]
