# Generated by Django 3.2.20 on 2023-08-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_recipemodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='type',
            field=models.CharField(choices=[('Starter', 'Starter'), ('Main', 'Main'), ('Dessert', 'Dessert')], max_length=7),
        ),
    ]
