# Generated by Django 3.2.20 on 2023-08-09 19:39

import cookypedia.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_recipemodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='recipe_photo',
            field=models.ImageField(upload_to='', validators=[cookypedia.core.validators.image_size_validator_5mb]),
        ),
    ]
