# Generated by Django 3.2.20 on 2023-08-13 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CocktailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cocktail_photo', models.ImageField(upload_to='photos_cocktails/')),
                ('type', models.CharField(choices=[('Alcoholic', 'ALCOHOLIC'), ('Non-Alcoholic', 'NON_ALCOHOLIC')], max_length=13)),
                ('ingredients', models.TextField()),
                ('method', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
