# Generated by Django 3.2.20 on 2023-08-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailmodel',
            name='cocktail_photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
