# Generated by Django 3.2.20 on 2023-08-13 19:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0023_alter_recipemodel_recipe_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_rename_to_photo_comment_to_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='RecipeComment',
        ),
    ]
