# Generated by Django 3.2.20 on 2023-08-13 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cocktail', '0001_initial'),
        ('core', '0003_rename_comment_recipecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CocktailComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=300)),
                ('date_time_of_publication', models.DateTimeField(auto_now_add=True)),
                ('to_cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktail.cocktailmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_time_of_publication',),
            },
        ),
    ]
