# Generated by Django 3.2.20 on 2023-08-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cocktailcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailcomment',
            name='comment_text',
            field=models.TextField(max_length=200),
        ),
    ]
